name: CLI

on: push

jobs:

  build:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
   
    - name: Restore package
      run: nuget restore

    - name: Build
      run: msbuild /t:Build /p:Configuration=Debug

    - name: Find Test DLL
      id: find-test-dll
      shell: pwsh
      run: |
        $dllPath = Get-ChildItem -Path CalcTesterTests\bin\Debug -Filter CalcTesterTests.dll -Recurse | Select-Object -First 1 -ExpandProperty FullName
        echo "Found DLL at: $dllPath"
        echo "TEST_DLL_PATH=$dllPath" >> $env:GITHUB_ENV

    - name: Tests
      run: vstest.console.exe ${{ env.TEST_DLL_PATH }}
